export const LIB_NAME = "HiSecure";
export const LIB_VERSION = "1.0.0";

// Adapter Names
export const ADAPTERS = {
    HASHING_PRIMARY: "HASHING_PRIMARY",
    HASHING_FALLBACK: "HASHING_FALLBACK",
    RATE_LIMITER: "RATE_LIMITER",
    VALIDATOR: "VALIDATOR",
    SANITIZER: "SANITIZER"
} as const;

// Manager Names
export const MANAGERS = {
    HASH_MANAGER: "HASH_MANAGER",
    RATE_LIMIT_MANAGER: "RATE_LIMIT_MANAGER",
    VALIDATION_MANAGER: "VALIDATION_MANAGER",
    SANITIZER_MANAGER:"SANITIZER_MANAGER"
} as const;

// Error Codes
export const ERROR_CODES = {
    ADAPTER_FAILURE: "ADAPTER_FAILURE",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    SANITIZER_ERROR:"SANITIZER_ERROR",
    CONFIG_ERROR: "CONFIG_ERROR",
    UNKNOWN: "UNKNOWN"
} as const;
